### ISSUE TITLE
Unexpected input(s) 'content', 'mentioned_list', valid inputs are ['msgtype']

### ISSUE THREAD

**Issue by hf-zhu** [chf007/action-wechat-work#13]
Unexpected input(s) 'content', 'mentioned_list', valid inputs are ['msgtype']

大佬 引用这个action报这个错误是啥问题能不能指导一下？

**Comment by chf007** [comment]
action 内容能贴一下么

**Comment by hf-zhu** [comment]
name: 定时提醒周报任务
 
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    # 可自定义 cron 表达式
    - cron: '30 1,2 * * 4'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 纯文本类型
      - name: GitHub Action for WeChat Work
        uses: ***@***.***
        env:
          PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
        with:
          msgtype: text
          content: 广州今日天气：29度，大部分多云，降雨概率：60%
          mentioned_list: ***@***.***"]' 谢谢你 非常感谢你 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chf007/action-wechat-work"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 中午1:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chf007/action-wechat-work] Unexpected input(s) 'content', 'mentioned_list', valid inputs are ['msgtype'] (Issue #13)





 
action 内容能贴一下么
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hf-zhu** [comment]
name: 定时提醒周报任务

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    # 可自定义 cron 表达式
    - cron: '30 1,2 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 纯文本类型
      - name: GitHub Action for WeChat Work
        uses: chf007/action-wechat-work@1.0.5
        env:
          PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
        with:
          msgtype: text
          content: 广州今日天气：29度，大部分多云，降雨概率：60%
          mentioned_list: '["@all"]

**Comment by chf007** [comment]
贴全了么？我看好像是缺引号

![image](https://user-images.githubusercontent.com/358650/146496475-7221b4ba-67b6-4801-b41a-f2f05eb5f16f.png)
![image](https://user-images.githubusercontent.com/358650/146496493-e6791167-fca4-4622-b11c-41650c98182f.png)

**Comment by hf-zhu** [comment]
name: 定时提醒周报任务

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    # 可自定义 cron 表达式
    - cron: '30 1,2 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 纯文本类型
      - name: GitHub Action for WeChat Work
        uses: chf007/action-wechat-work@1.0.5
        env:
          PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
        with:
          msgtype: text
          content: 广州今日天气：29度，大部分多云，降雨概率：60%
          mentioned_list: '["@all"]'

**Comment by hf-zhu** [comment]
没有复制完成 不缺引号，谢谢你的回复  真挚感谢，

**Comment by chf007** [comment]
问题解决了么

**Comment by hf-zhu** [comment]
没有呢 大佬 你用我的那个action跑的有没有问题？

**Comment by chf007** [comment]
> 

我看了下我的 action 也有这个提示，但这只是一个警告，并不影响功能的使用，消息还是能发出的，有警告可能是最近 Actions 用法有变，我要再看一下。

如果你的还是发不出可能是环境变量设的有问题？我看并没有设置 `WECHAT_WORK_BOT_WEBHOOK` 这个环境变量，只有 PUSH_PLUS_TOKEN

![image](https://user-images.githubusercontent.com/358650/146713420-8e5c6409-295a-4333-88d4-3b231058cb66.png)

**Comment by hf-zhu** [comment]
WECHAT_WORK_BOT_WEBHOOK必须要用这个名字么？ 我以为改个名字也行，我确实没有使用这个环境变量名。谢谢你

**Comment by chf007** [comment]
必须要用这个名字

**Comment by hf-zhu** [comment]
谢谢你 把这个改了就好了，还是有warning。

**Comment by chf007** [comment]
warning 已经消除了，可以使用最新版体验一下
