### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by sukki37** [chf007/action-wechat-work#15]
推送的时候会报错
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/77312370/165101495-a3ed9ce5-3a47-4e4f-8a8f-b92aa2edf0bc.png">

**Comment by chf007** [comment]
应该是企微接口报错了，但是对异常返回的值处理考虑的场景不全，这个会解决掉。

当前状态可以多试一下，或者看看是否格式有问题。

**Comment by chf007** [comment]
1.0.7 内已更新 ，可以再试下

**Comment by sukki37** [comment]
还是一样的，而且非常奇怪，在fork出来的分支跑并不会报错，但是在主库跑的时候就会报这个错
<img width="957" alt="image" src="https://user-images.githubusercontent.com/77312370/165794936-78ccd5ab-b89b-4a40-acb5-36dc050acf32.png">

**Comment by chf007** [comment]
> 还是一样的，而且非常奇怪，在fork出来的分支跑并不会报错，但是在主库跑的时候就会报这个错 <img alt="image" width="957" src="https://user-images.githubusercontent.com/77312370/165794936-78ccd5ab-b89b-4a40-acb5-36dc050acf32.png">

看看是不是 markdown 格式问题，这个报错应该是企业微信接口报的，可以把上边的 JSON 在本地用 curl 测一下
